### ISSUE TITLE
Ctrl-Alt-B runs the app even if the build failed

### ISSUE THREAD

**Issue by YaLTeR** [bilelmoussaoui/flatpak-vscode#11]
Ctrl-Alt-B runs the app even if the build failed. 

This occurs at least for Rust projects.

**Comment by Hofer-Julian** [comment]
Yeah, @bilelmoussaoui is currently working on it.
Still good to have it listed here.
Thanks for reporting 😊

**Comment by bilelmoussaoui** [comment]
Yes, the current vscode tasks api doesn't allow us to check if a task was successfully finished or not and as we don't have access to the stdout neither we have to do some dirty hacks to get around it. I have a half working prototype, I will try to finish it as soon as I can
