### ISSUE TITLE
Specificy indent size for typescript 

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#112]
The .editorconfig doesn't specify something for .ts so we default to 4 spaces but the files seems to be mixed. We should decide on one and fix the existing files

**Comment by bilelmoussaoui** [comment]
> I do prefer 4 spaces

Me too, I will handle that then

**Comment by bilelmoussaoui** [comment]
I did the 4 spaces part, although, I am not really fan of the semicolons because they don't serve much :/

**Comment by SeaDve** [comment]
I'm fine with or without, so I guess let's keep that off
