### ISSUE TITLE
OutputTerminal acts weird on resize

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#115]
There are probably events that should be watched then resize the IPty accordingly

**Comment by SeaDve** [comment]
> Something else I noticed about the output terminal, there is now to make it auto scroll; maybe could be an option.

It does auto scroll for me in the defaults.

**Comment by bilelmoussaoui** [comment]
> > Something else I noticed about the output terminal, there is now to make it auto scroll; maybe could be an option.
> 
> It does auto scroll for me with the default.

It does auto scroll if you are the bottom of the terminal, otherwise it gets a bit weird :/
