### ISSUE TITLE
Investigate on Uri.fsPath accessing

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#118]
See #116 discussion

**Comment by bilelmoussaoui** [comment]
I don't think there is much to investigate here really, the issue is when serializing the pipeline state and we no longer do this, but worth looking at vscode.Uri API to see whether the fsPath is optional or not

**Comment by SeaDve** [comment]
It is not optional, but it is really weird how it is was undefined in your case. What was the error when you noticed something went wrong while migrating?

**Comment by SeaDve** [comment]
Checked on vscode sourcecode. The fsPath is a getter and not a field (basically a wrapper for `uriToFsPath`). So if it errors in your case while accessing fsPath, it is still weird

**Comment by bilelmoussaoui** [comment]
> It is not optional, but it is really weird how it is was undefined in your case. What was the error when you noticed something went wrong while migrating?

There was no errors at all, when I went through the migration code with a debugger I noticed it stops at the check if the pipeline state file exists. Did a console.log and notice it is actually null.

**Comment by bilelmoussaoui** [comment]
And I think you are still mis-understanding the migration issue here, we don't access the same fsPath, it is no longer a vscode.Uri we have once we store and then load the pipeline state file, it is a json object.

**Comment by SeaDve** [comment]
I see, so we I think we can close this?

**Comment by bilelmoussaoui** [comment]
> Although, based on the interface LegacyState, isn't it still being deserialized into Uri?

Oh that is something I missed. Maybe we should try to serialize a vscode.Uri and then deserialize it and see what it still has as properties?

**Comment by SeaDve** [comment]
I'll try.

**Comment by SeaDve** [comment]
I guess I figured it out. JS is full of weirdness. 

fsPath is only defined when it was called. I guess it is memoized of some sort.

fsPath is defined:
```js
const uri = vscode.Uri.file('/home/test')
    console.log(uri.fsPath)
    const serialized = JSON.stringify(uri)
    console.log(serialized)
    const deserialized = JSON.parse(serialized) as vscode.Uri
    console.log(deserialized)
    console.log(deserialized.fsPath)
```

fsPath is undefined:
```js
const uri = vscode.Uri.file('/home/test')
    const serialized = JSON.stringify(uri)
    console.log(serialized)
    const deserialized = JSON.parse(serialized) as vscode.Uri
    console.log(deserialized)
    console.log(deserialized.fsPath)
```

**Comment by SeaDve** [comment]
I'll see if Memento has the same problem.

**Comment by bilelmoussaoui** [comment]
Thanks for investigating!
