### ISSUE TITLE
Don‘t trigger a „run“ when executing „rebuild“

### ISSUE THREAD

**Issue by Hofer-Julian** [bilelmoussaoui/flatpak-vscode#12]
Most IDEs only rebuild the app when being asked to execute „rebuild“. It is not expected that the app will also be run.

It also doesn‘t fit nicely with debugging, because here the app will be run differently.

**Comment by bilelmoussaoui** [comment]
I think one of the ways we could simplify this is by storing the pipeline state on a file & loading from it in the future. This would allow us to know if we already built the app (means _build dir in case of meson for example is initialized) & then we can just make build do what rebuild does and remove it.
The issue we will have is we can't really do something fancy when you click on the run button, Builder here, checks the buildsystem and rebuilds if there were any code changes. While us will just run the latest build and you keep wondering why your changes are not applied :P

**Comment by bilelmoussaoui** [comment]
I'm tempted to close this, the rebuild here is mostly like hitting the run button in builder. It does a rebuild & run. Regarding debug, it would have to be integrated manually where a build would be followed up by running the app with say gdb

**Comment by Hofer-Julian** [comment]
Yeah, I think we discussed this, and identified the main problem in the name. Rebuild alone shouldn't run, but calling it "Rebuild+run" is fine.
