### ISSUE TITLE
Not able to spawn 'dotnet' or 'dotnet --info'

### ISSUE THREAD

**Issue by aarshparashar** [bilelmoussaoui/flatpak-vscode#132]
Installing C# dependencies...
Platform: linux, x86_64, name=org.freedesktop.platform, version=21.08.10

Finished

Failed to spawn 'dotnet --info'

**Comment by bilelmoussaoui** [comment]
Which application you are trying to build? Also we don't have any integrations with C# extensions, see #75

**Comment by aarshparashar** [comment]
When can we expect it?

> Which application you are trying to build? Also we don't have any integrations with C# extensions, see #75

**Comment by bilelmoussaoui** [comment]
Needs someone familiar with C# to at least give us an application that can be built with a flatpak manfiest and the extensions they use

**Comment by aarshparashar** [comment]
> Needs someone familiar with C# to at least give us an application that can be built with a flatpak manfiest and the extensions they use 

Okay, is it possible to start with a simple console application? I can do the testing work but I'm not that familiar with making Flatpak packages and extensions.

**Comment by SeaDve** [comment]
You can use an existing manifest so we can replicate the issue you're having.

**Comment by aarshparashar** [comment]
> You can use an existing manifest so we can replicate the issue you're having.

I was using org.freedesktop.Sdk.Extension.dotnet6 beta. VS Code was not able to spawn runtime which can be usually done using 'dotnet' in shell.

**Comment by aarshparashar** [comment]
Guys add Docker and other OCI runtimes too.

**Comment by bilelmoussaoui** [comment]
I think you are mis-understanding what this extension do, it doesn't make VScode suddenly uses the binaries shipped as part of the SDKs. It only does that in case you have an application with a Flatpak manifest in-tree and even then, it doesn't do that for the normal vscode terminals, instead you will have to open a build terminal to get all the tools that are part of your application up and running. 

Once there is a manifest and the #75 handles whatever SDK extensions you are using, then other VSCode extensions could easily be made to run their binaries inside the flatpak sandbox making it not necessary to have the required dependencies to run say, a language server (for autocompletion) installed on the host as they will be run inside the flatpak container.

I am going to go ahead and close this one as there is nothing actionable from our side here, we can't make VSCode change the way it runs everything nor the way the vscode extensions do so.

**Comment by aarshparashar** [comment]
As you wish.
