### ISSUE TITLE
Exceptions on clean up build directory

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#158]
if `_build` or `.flatpak/repo` does not exist. It will throw an error, causing subsequent commands to not be ran.

The fix is to just put `force: true`. I'll submit a PR after #150 is merged to prevent conflicts on that.

**Comment by bilelmoussaoui** [comment]
Yeah, I noticed that today as well. I had to re-create the folders manually in order to do a cleanup

**Comment by bilelmoussaoui** [comment]
Actually there is no `force` option for RmDirOptions, so I added a check that the dirs exists.
