### ISSUE TITLE
Watch manifest & update state accordingly

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#17]
In case the user modified the manifest to add a dependency, we should automatically offer to re-build or auto-update the config at least.

**Comment by SeaDve** [comment]
I think offering to rebuild every modification may be interruptive, so maybe config updates would suffice

**Comment by bilelmoussaoui** [comment]
> I think offering to rebuild every modification may be interruptive, so maybe config updates would suffice.
> 
> Except maybe when a module is modified

yes that is exactly what I was thinking of
