### ISSUE TITLE
flatpak-builder can't be used as-is inside a container/toolbox, requires `--disable-rofiles-fuse` option

### ISSUE THREAD

**Issue by 1player** [bilelmoussaoui/flatpak-vscode#186]
`flatpak-builder` requires the `--disable-rofiles-fuse` option to work inside a container, see https://github.com/flatpak/flatpak/issues/647

Otherwise commands fail with cryptic errors such as:

```
error: Build directory /var/home/sph/Code/github.com/flathub/org.develz.Crawl/.flatpak/flatpak-builder/rofiles/rofiles-eFZUFH not initialised, use flatpak build-init
Error: module glu: Child process exited with code 1
```

Please give us a wat to add that option, or make the arguments to `flatpak-builder` configurable.

**Comment by bilelmoussaoui** [comment]
How are you running vscode to have this issue?

**Comment by 1player** [comment]
Inside the container, because it's the only way to skirt around the limitations of the Flatpak version of vscode and the fact that I'm running Fedora Silverblue.

**Comment by bilelmoussaoui** [comment]
I see, I wonder if there is some way to detect you are running vscode inside a container, at least for cases like toolbox/distrobox so that --disable-rofiles-fuse is automatically added for you without the need of a configuration.

**Comment by 1player** [comment]
There's a few ways, but none that are official. For example, this podman container has a `/run/.containerenv` file which could be used to determine that it is in fact a container.

Toolbox creates `/run/.toolboxenv`

**Comment by bilelmoussaoui** [comment]
If you want to give a try to fix the issue, the change should be rather minimal, see https://github.com/bilelmoussaoui/flatpak-vscode/blob/master/src/command.ts#L79-L92. Basically you need to append --disable-rofiles-fuse to args if we are running inside a toolbox/distrobox container.

**Comment by 1player** [comment]
Thanks, I'll look into it. I just learned from that code that this can use a flatpak version of flatpak-builder. Looking at the org.flatpak.Builder manifest, it seems they patched the binary and its fuse dependency to avoid this issue.

**Comment by bilelmoussaoui** [comment]
That code path is not part of a release yet, so if we can fix your use case as well, i can roll a release afterwards.

**Comment by bilelmoussaoui** [comment]
Would you mind trying the extension with the changes on https://github.com/bilelmoussaoui/flatpak-vscode/pull/189? you can check the contributing file for how to start vscode with a devel version of the extension.
