### ISSUE TITLE
Report an error when the current build failed, instead of continueing by running the last successful build.

### ISSUE THREAD

**Issue by flxzt** [bilelmoussaoui/flatpak-vscode#194]
Currently the last successful build is run when executing the `Build and run the application` action, even when the current build has failed.
This is confusing when you don't always look at the output too closely on each build. 

I remember that the extension used to report an error to vscode when a build has failed in a previous version, maybe the behaviour could be reverted to that?

**Comment by bilelmoussaoui** [comment]
I just tried what you are saying and "build and run" definitely stops at the "build" stage if there was an error. Do you have a manifest I can try with or if you still can reproduce the issue in the recent version?

**Comment by flxzt** [comment]
sorry, I just checked and noticed that this was an issue in my build script
