### ISSUE TITLE
Unable to find blueprint-compiler for use in build

### ISSUE THREAD

**Issue by u1f98e** [bilelmoussaoui/flatpak-vscode#196]
I'm trying to build [Gradience](https://github.com/GradienceTeam/Gradience) using its Devel manifest, but get stopped by the final meson configuration: 
```
Program blueprint-compiler found: NO

data/ui/meson.build:1:0: ERROR: Program 'blueprint-compiler' not found or not executable
```
`blueprint-compiler` does exist in the manifest, and running flatpak-builder manually successful builds. (`Program blueprint-compiler found: YES (/app/bin/blueprint-compiler)`).

I can run 
```bash
flatpak-builder --state-dir=.flatpak/flatpak-builder --force-clean .flatpak/repo build-aux/flatpak/com.github.GradienceTeam.Gradience.Devel.json
```
after unsuccessfully building with the extension and it builds using the previous cache just fine, the extension can't run the result though as it tries to build again.

Here's the build log's section for `blueprint-compiler` in case it's helpful: https://pastebin.com/d4yCfzqH

**Comment by bilelmoussaoui** [comment]
I just tried building the Devel manifest and it works just fine here
