### ISSUE TITLE
No Flatpak manifest found in this workspace.

### ISSUE THREAD

**Issue by mijorus** [bilelmoussaoui/flatpak-vscode#199]
terminal output:

```
2023-01-03 14:33:13.888 [error] Error: No Flatpak manifest found in this workspace.
    at ManifestManager.<anonymous> (/home/me/.vscode/extensions/bilelmoussaoui.flatpak-vscode-0.0.30/out/manifestManager.js:214:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/me/.vscode/extensions/bilelmoussaoui.flatpak-vscode-0.0.30/out/manifestManager.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) flatpak-vscode.build-and-run {"value":"bilelmoussaoui.flatpak-vscode","c":"bilelmoussaoui.flatpak-vscode"}

```

it happens at radom, sometimes it works sometimes it does not

**Comment by SeaDve** [comment]
Can you show the steps in reproducing the error?

**Comment by mijorus** [comment]
Quite simply, I open a folder which directly contains a flatpak manifest

**Comment by SeaDve** [comment]
No commands were ran?

**Comment by mijorus** [comment]
@SeaDve what do you mean with `commands`?

- terminal commands
- VS code commands (ctrl + shift + p)
- commands ran by other extensions?

**Comment by caspermeijn** [comment]
I have the same issue. I re-opened a project that previously worked fine. Now it tells me that "No Flatpak manifest found in this workspace". 

![Schermafdruk van 2023-04-01 12-10-00](https://user-images.githubusercontent.com/1286074/229280362-bc71e1a2-6929-4829-93a8-746d26aa05ea.png)

**Comment by caspermeijn** [comment]
I did some debugging of the plugin. It had a lot of log entries for "Trying to parse potential Flatpak manifest ". These were all in the `build-dir` directory of a previous manual `flatpak-builder` run. After deleting `build-dir` the plugin worked as expected. Is there a maximum number of files it tries to parse? Maybe a different message show be shown when the maximum is reached?

**Comment by SeaDve** [comment]
> I did some debugging of the plugin. It had a lot of log entries for "Trying to parse potential Flatpak manifest ". These were all in the `build-dir` directory of a previous manual `flatpak-builder` run. After deleting `build-dir` the plugin worked as expected. Is there a maximum number of files it tries to parse? Maybe a different message show be shown when the maximum is reached?

It might be caused by this limit: https://github.com/bilelmoussaoui/flatpak-vscode/blob/eab905106292c343c9ac47eccadaa0427f85886a/src/manifestUtils.ts#L24

**Comment by bilelmoussaoui** [comment]
> 

I guess the real issue is on the ignore glob pattern at https://github.com/bilelmoussaoui/flatpak-vscode/blob/eab905106292c343c9ac47eccadaa0427f85886a/src/manifestUtils.ts#L23
