### ISSUE TITLE
run-tests property isn't recognized 

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#20]
![Screenshot from 2021-01-15 02-35-01](https://user-images.githubusercontent.com/7660997/104669445-4c6cf380-56da-11eb-8e63-ba5f1056f2ab.png)

**Comment by Hofer-Julian** [comment]
On master?

**Comment by bilelmoussaoui** [comment]
Ah found what caused it :p it was a typo
