### ISSUE TITLE
Unicode character can't show

### ISSUE THREAD

**Issue by GZYangKui** [bilelmoussaoui/flatpak-vscode#203]
I use gnome-builder to run my display. There is no problem. There is a problem when using the flatpak-vscode and the following exception message appears:
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml

flatpak plugin:
![image](https://user-images.githubusercontent.com/40876227/225235659-4d2a6a1a-4ed4-4104-83ec-fa4be48b012b.png)
gnome-builder:
![image](https://user-images.githubusercontent.com/40876227/225235779-5279c82e-e00c-4537-8bec-ef991a86d247.png)

**Comment by bilelmoussaoui** [comment]
We would need to do something similar to what is done here https://gitlab.gnome.org/ZanderBrown/fenv/-/merge_requests/18. If someone wants to submit a patch :)
