### ISSUE TITLE
Fontcache error with v0.0.33

### ISSUE THREAD

**Issue by dubstar-04** [bilelmoussaoui/flatpak-vscode#208]
When using version 0.0.33 I get the following error when building:
bwrap: Can't find source path /usr/lib/fontconfig/cache: No such file or directory

using v0.0.31 works fine.

**Comment by bilelmoussaoui** [comment]
Is VSCode installed from Flathub?

**Comment by dubstar-04** [comment]
yes VS Code from flathub:
![image](https://user-images.githubusercontent.com/1136710/231160064-ca3c2e47-ec94-4fd2-9de9-be2d3883be66.png)

**Comment by bilelmoussaoui** [comment]
What is the base os you are using? and is `/usr/lib/fontconfig/cache` exists on the host?

**Comment by dubstar-04** [comment]
I'm using Debian testing. I don't have that directory on the host as noted above; using v0.0.31 works fine.

**Comment by bilelmoussaoui** [comment]
Could you paste the whole command that got used at build stage before failure?

**Comment by bilelmoussaoui** [comment]
I think i know the cause of the issue, we are running https://github.com/bilelmoussaoui/flatpak-vscode/blob/master/src/utils.ts#L80 inside the sandbox which is wrong. we should be using flatpak-spawn there. I will prepare a patch and do a release afterwards

**Comment by dubstar-04** [comment]
I can confirm that it is fixed for me with v0.0.34. Thank you!

**Comment by bilelmoussaoui** [comment]
awesome :)
