### ISSUE TITLE
Vala language server fails to start: vala-language-server.sh file does not exist

### ISSUE THREAD

**Issue by nahuelwexd** [bilelmoussaoui/flatpak-vscode#215]
Due to a recent change where `${workspaceFolder}` is now used (#211), the Vala language server cannot start. This may be because VS Code does not resolve the `${workspaceFolder}` variable in settings.json, so it passes the string as-is to the Vala extension.

I'm not quite sure that it is really advisable to assume that extensions will handle variables exposed by VS Code in other scopes.

**Comment by bilelmoussaoui** [comment]
> so it passes the string as-is to the extension.

That is not really true. See https://github.com/bilelmoussaoui/flatpak-vscode/blob/master/src/manifest.ts#L641

**Comment by nahuelwexd** [comment]
I meant that VS Code passes the string "${workspaceFolder}/.flatpak/vala-language-server.sh" to the Vala extension, instead of expanding `${workspaceFolder}` and then passing the full path to the Vala extension.

**Comment by caspermeijn** [comment]
I created a patch for the Vala extension. This works on my machine. Can you verify this fixes your problem?

https://github.com/vala-lang/vala-vscode/pull/25

**Comment by nahuelwexd** [comment]
I was testing the approach that Meson extension uses for the `vscode_compile_commands.json` file, which is to simply use neither absolute path nor the `${workspaceFolder}` variable, but just use the relative path: `_build/vscode_compile_commands.json`.

It seems to work

I will be testing your patch for the Vala extension.

**Comment by caspermeijn** [comment]
Removing `${workspaceFolder}` seems to fail for the Rust extension. It seems there is not a "one size fits all" solution. 

I think the patch to the Vala extension is the way to go.

**Comment by bilelmoussaoui** [comment]
Is this still happening with latest release?

**Comment by nahuelwexd** [comment]
@bilelmoussaoui this is still hapenning, but the solution will be just to patch the Vala extension an that's it

**Comment by bilelmoussaoui** [comment]
Let us close this one then . Feel free to open an issue on the vala sdk extension side

**Comment by lw64** [comment]
> @bilelmoussaoui this is still hapenning, but the solution will be just to patch the Vala extension and that's it

Do you mean the Vala Sdk or the vala-vscode plugin?

**Comment by nahuelwexd** [comment]
@lw64 the vala-vscode plugin

**Comment by lw64** [comment]
So the flatpak-vscode plugin is currently broken with vala?

**Comment by nahuelwexd** [comment]
@lw64 kinda

**Comment by lw64** [comment]
If its broken, then thats definitly a problem that needs to be fixed. Using the vala-vscode extension is not a good solution, as you need the language server for it installed on the host. I am sadly not much into vscode extensions, so I don't know what is the issue here and how to fix it. Also what does "kinda" mean? Does it work sometimes, and sometimes not?

**Comment by caspermeijn** [comment]
@nahuelwexd @lw64 The new release of vala-vscode v1.1.0 has the fix for this issue: https://github.com/vala-lang/vala-vscode/releases/tag/v1.1.0

Can you verify that this fixes your problem and report back?

**Comment by nahuelwexd** [comment]
@caspermeijn I tested your PR in advance, and I already tested the new release, everything works as expected

**Comment by caspermeijn** [comment]
Great to hear this is fixed.
