### ISSUE TITLE
IntelliJ version

### ISSUE THREAD

**Issue by Skaldebane** [bilelmoussaoui/flatpak-vscode#220]
Hi there!

Are there any plans to create an IntelliJ version of this extension? I'm working on a Rust project (based on the `gtk-rust-template`) and I find CLion / IntelliJ IDEA a lot more ergonomic to work with compared to VS Code for Rust code.

I can help with anything if needed.

And thanks a lot for this amazing extension!

**Comment by bilelmoussaoui** [comment]
Hi, 

I don't really have any bandwidth left to start yet another project anytime soon, even less for something I won't use personally. If you or someone else ended up working on this, I would be happy to help by sharing whatever knowledge I gained when developing this extension.

Thank you

**Comment by Skaldebane** [comment]
Hi!
I talked about this with you on Matrix a while after I filed this.
I'll give it a shot, and I'll shoot you a message there should I need help.
Thanks!
