### ISSUE TITLE
rust-analyzer is using all memory

### ISSUE THREAD

**Issue by abergmeier** [bilelmoussaoui/flatpak-vscode#226]
When I open a rust project in VSC it takes around 4GB of memory.
When I open a rust project with VSC and flatpak rust-analyzer takes all my memory (16GB) and apps then become unresponsive and crash.

**Comment by bilelmoussaoui** [comment]
I think it is a duplicate of https://github.com/bilelmoussaoui/flatpak-vscode/issues/222
