### ISSUE TITLE
Path to rust analyzer nightly cargo has changed

### ISSUE THREAD

**Issue by felinira** [bilelmoussaoui/flatpak-vscode#244]
I happened to find myself in the situation of needing a nightly compiler for a while. Anyway, apparently its path has changed. It now seems to be at `/usr/lib/sdk/rust-nightly/extra/sdk/rust-nightly/bin`.

The change was probably https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-nightly/commit/f519a05f6c1fc721e071eb0b54bcede0cf73fbfb

**Comment by bbhtt** [comment]
Can you check if it is working with the latest update?
