### ISSUE TITLE
Build dir not initialized (when running Build the application)

### ISSUE THREAD

**Issue by toger5** [bilelmoussaoui/flatpak-vscode#34]
When running the follwing command:
`Flatpak: Build the application` the following error is raised
```
> flatpak build --share=network --nofilesystem=host --filesystem=<project_path> --filesystem=<project_path>/.flatpak/repo --env=PATH=$PATH:/usr/lib/sdk/rust-stable/bin --env=RUSTFLAGS=--remap-path-prefix =../ --env=CARGO_HOME=/run/build/project_name/cargo --env=RUST_BACKTRACE=1<project_path>/.flatpak/repo cargo fetch --manifest-path Cargo.toml --verbose <
error: Build directory =../ not initialized, use flatpak build-init
```

**Comment by bilelmoussaoui** [comment]
That's interesting, do you have your project somewhere so I can give it a try locally?

**Comment by bilelmoussaoui** [comment]
Oh, remove the --remp-path-prefix from your manifest, restart vscode and try again?

**Comment by toger5** [comment]
The project is here: https://github.com/toger5/Spectre-gtk
(I will try your propesed changed and edit this message)

**Comment by bilelmoussaoui** [comment]
All good then, thanks for confirming it works!
