### ISSUE TITLE
flatpak-builder errors when trying to build a dependency

### ISSUE THREAD

**Issue by melix99** [bilelmoussaoui/flatpak-vscode#35]
I'm trying to use this extension to easily build my project using flatpak, but when I try to build it, it fails with this output:

```shell
> flatpak-builder --ccache --force-clean --disable-updates --disable-download --build-only --keep-build-dirs --state-dir=/home/melix/Git/melix99/telegrand/.flatpak/flatpak-builder --stop-at=telegrand /home/melix/Git/melix99/telegrand/.flatpak/repo /home/melix/Git/melix99/telegrand/build-aux/com.github.melix99.telegrand.Devel.json <
Emptying app dir '/home/melix/Git/melix99/telegrand/.flatpak/repo'
Initializing build dir
Committing stage init to cache
Starting build of com.github.melix99.telegrand.Devel

(flatpak-builder:2045): flatpak-builder-WARNING **: 18:04:18.721: Failed to get current git checksum: Failed to change to directory “/home/melix/Git/melix99/telegrand/.flatpak/flatpak-builder/git/https_gitlab.gnome.org_GNOME_libadwaita.git” (No such file or directory)
========================================================================
Building module libadwaita in /home/melix/Git/melix99/telegrand/.flatpak/flatpak-builder/build/libadwaita-1
========================================================================
cp: cannot stat '/home/melix/Git/melix99/telegrand/.flatpak/flatpak-builder/git/https_gitlab.gnome.org_GNOME_libadwaita.git': No such file or directory
Error: module libadwaita: Child process exited with code 1
```

If needed, the project which I'm trying to build is [this](https://github.com/melix99/telegrand) (use the rewrite branch as the flatpak support is only there). BTW, it builds just fine with gnome-builder.

**Comment by bilelmoussaoui** [comment]
You need to run the update dependencies, the build deps and then you can build the app. Sadly we are not as nicely integrated as builder

**Comment by melix99** [comment]
Yeah, it seems to work now, thanks!

I think that we should tweak the notifications that let the user build their projects. I mean, the first notification that I received was about initializing the project and the next one was already about building the project. I think that it makes sense to send a notification about updating the dependencies before the one about building the project, so maybe the process is a bit more straightforward.

**Comment by melix99** [comment]
> Yeah, it seems to work now, thanks!

Spoken too soon, the dependencies and the project seems to have been built successfully, but when I try to run the "Flatpak: Run" command, it gives me this output:

```shell
bwrap: Can't find source path /run/user/1000/doc/by-app/com.github.melix99.telegrand.Devel: No such file or directory
```

**Comment by bilelmoussaoui** [comment]
> > Yeah, it seems to work now, thanks!
> 
> Spoken too soon, the dependencies and the project seems to have been built successfully, but when I try to run the "Flatpak: Run" command, it gives me this output:
> 
> ```shell
> bwrap: Can't find source path /run/user/1000/doc/by-app/com.github.melix99.telegrand.Devel: No such file or directory
> ```

that often means the documents portal is not running or crashed for whatever reasons:
```
systemctl --user restart xdg-document-portal.service
```
this should help 





> Yeah, it seems to work now, thanks!
> 
> I think that we should tweak the notifications that let the user build their projects. I mean, the first notification that I received was about initializing the project and the next one was already about building the project. I think that it makes sense to send a notification about updating the dependencies before the one about building the project, so maybe the process is a bit more straightforward.

Ideally yes, it's still in preview. I just got it to a stage of "ok it kind of works" for my own use cases for now

**Comment by melix99** [comment]
> that often means the documents portal is not running or crashed for whatever reasons

Yeah, that was it. Thanks again :)

> I just got it to a stage of "ok it kind of works" for my own use cases for now

Understandable, I'll see if I can contribute one day to improve its workflow.
