### ISSUE TITLE
Don't search for the manifest in ignored directories

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#45]
If you have a dependency (say ashpd) it will find the ashpd-demo manifest first and use it which is not great

**Comment by SeaDve** [comment]
as far as I know, `workspace.findFiles` respects `files.exlude` settings

**Comment by bilelmoussaoui** [comment]
I had the ashpd demo manfiest detected when working on Authenticator with ashpd used from git instead of the crates.io

**Comment by SeaDve** [comment]
I see, won't be an issue now if you can select manifest :)

**Comment by bilelmoussaoui** [comment]
indeed :)

**Comment by bilelmoussaoui** [comment]
I can no longer reproduce this lately so let us close it
