### ISSUE TITLE
bwrap: Can't find source path /run/user/1000/doc/by-app/${app_id}: No such file or directory

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#48]
VS Code version: 1.64.0 (host, official vscode yum repo)
Flatpak vscode extension version: 0.0.16

It basically only happens every bootup. A weird workaround is to close vscode and open any other flatpak app in host. Then reopen vscode, now everything works properly. The workaround lasts, until another boot. I think something may not be initialized during the configuration of the extension.

Steps to reproduce:
1. Boot device
2. Open vscode
3. Open build terminal or trigger rust analyzer

Output:
`bwrap: Can't find source path /run/user/1000/doc/by-app/${app_id}: No such file or directory`

**Comment by bilelmoussaoui** [comment]
That is the document portal not being started yet

**Comment by SeaDve** [comment]
I'm currently experimenting on fixing it

**Comment by SeaDve** [comment]
one problem is some other extension, like r-a loading first before ensuring the document portal, causing it to fail

**Comment by bilelmoussaoui** [comment]
Ah that could be problematic indeed. Sadly, we don't control that from the extension, but maybe there is some priority that can be set in manifest.json

**Comment by bilelmoussaoui** [comment]
After a quick look, that doesn't seem to be the case which is unfortunate :/ but I guess it is better with your changes then nothing.

**Comment by SeaDve** [comment]
how does gnome-builder handles it?

**Comment by bilelmoussaoui** [comment]
well builder runs that probably super early before any other extension has started

**Comment by bilelmoussaoui** [comment]
right, but builder is built for flatpak, so it probably has some kind of way to tell which to runs first

**Comment by SeaDve** [comment]
ill investigate on how builder does it
