### ISSUE TITLE
"Flatpak manifest detected" is always appearing every startup

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#50]
I'm not sure if it is intended or a bug. If it is intended, there could be a don't show again, or automatically init a build every launch

**Comment by bilelmoussaoui** [comment]
it is a bug, because we show it before we have parsed the status of the pipeline

**Comment by bilelmoussaoui** [comment]
It shouldn't be hard to do, we need to add a new attribute to the state to tell if the state was loaded from the disk or not yet and wait for that to be set to something before deciding whether to show the dialog or not
