### ISSUE TITLE
Add way to cancel/stop a build

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#54]
Currently, i use reload window to cancel a build

I'm not sure if it is fine to just kill the child process

**Comment by SeaDve** [comment]
just realized there is a close method

**Comment by bilelmoussaoui** [comment]
That shouldn't be hard to implement, the issue is where to add such action

**Comment by SeaDve** [comment]
in the command palette?

I do have a local branch though that adds a run and close button to the editor toolbar, if that is what you mean

**Comment by SeaDve** [comment]
that seems doable. The current problem i had is I couldn't terminate the process properly. I'll push the wip branch into a pr
