### ISSUE TITLE
Output channel is noticeably delayed

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#56]
It probably waits a few moments before flushing the line. The delay could be problematic when watching logs

**Comment by bilelmoussaoui** [comment]
the whole output approach is not great but that is all vscode offers to us :( all the other approaches are more limited. Maybe there is something mis-configured on `readline` part? that is all I can think of

**Comment by bilelmoussaoui** [comment]
That won't work though because we need to chain up multiple commands and there is no way to know if one has crashed or not

**Comment by SeaDve** [comment]
ill see if pseudoterminal would be ideal in our case

**Comment by bilelmoussaoui** [comment]
I did my attempt with it a few releases in the past and it didn't work that well sadly, maybe you will have better luck on that

**Comment by SeaDve** [comment]
it seems to work well, and the delay is gone, plus it acts now as an actual terminal (like clickable paths). But I couldn't get ansi colors to work

**Comment by bilelmoussaoui** [comment]
>  But I couldn't get ansi colors to work as of now

I didn't managed to do that neither last time
