### ISSUE TITLE
build-init terminates with exit code 1

### ISSUE THREAD

**Issue by fushinari** [bilelmoussaoui/flatpak-vscode#6]
build-init terminates with exit code 1. Logs:
```
> Executing task: flatpak build-init ~/Projects/dialect/.flatpak/repo com.github.gi_lom.dialect org.gnome.Sdk org.gnome.Platform master <

error: org.gnome.Sdk/*unspecified*/master not installed
The terminal process "/usr/bin/zsh '-c', 'flatpak build-init ~/Projects/dialect/.flatpak/repo com.github.gi_lom.dialect org.gnome.Sdk org.gnome.Platform master'" terminated with exit code: 1.
```

Here we see the command executed includes `org.gnome.Sdk org.gnome.Platform master`.
However, the runtime-version specified in the Flatpak's manifest is 3.38 as seen [here](https://github.com/gi-lom/dialect/blob/main/build-aux/flatpak/com.github.gi_lom.dialect.json). So, `master` is the wrong version.

Looking at the code, the culprit could be:
https://github.com/bilelmoussaoui/flatpak-vscode/blob/d16489460c89d1d4d54fb500e4108839936806b2/src/tasks.ts#L119

I think `runtime-version` might be more appropriate here than `branch`.

**Comment by bilelmoussaoui** [comment]
Install the Sdk manually first. We can't parse and prompt the user to install one.
Though such issue should indeed be fixed

**Comment by fushinari** [comment]
No, I mean the issue is that the flatpak only requires 3.38 Sdk and Runtime. But the extension executes the build-init command with the `master` version instead.

**Comment by fushinari** [comment]
I see my original comment was not descriptive enough. I've updated it. Hopefully that clears it up.

**Comment by bilelmoussaoui** [comment]
No worries, I've got what you meant :) Fixed! I will do a patch release later tonight, feel free to try it afterwards. Currently, we can't detect when a task (command line) failed, so we can't really do anything fancy like #1

**Comment by fushinari** [comment]
Thank you! Btw, I'm especially liking your work with bringing Flatpak support to more commonly used platforms and tools like with this extension and also the Flatpak GitHub action. So, thanks for your work with that!

**Comment by bilelmoussaoui** [comment]
Happy to help :)
