### ISSUE TITLE
Handle --require-version properly

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#61]
- [ ] First be removed from the finish-args at https://github.com/bilelmoussaoui/flatpak-vscode/blob/master/src/flatpakManifest.ts#L62-L75 because it is problematic for flatpak-builder like the --metadata one
- [ ] Set the required version as a FlatpakManifest attribute
- [ ] Get the `flatpak --version` and store it when the extension starts 
- [ ] Show an error message if version < minRequiredVersion for any step that the user might want to try

**Comment by SeaDve** [comment]
where is this currently handled?

**Comment by bilelmoussaoui** [comment]
It is not, but ideally it would:
- First be removed from the finish-args at https://github.com/bilelmoussaoui/flatpak-vscode/blob/master/src/flatpakManifest.ts#L62-L75 because it is problematic for flatpak-builder like the --metadata one
- Set the required version as a FlatpakManifest attribute
- Get the `flatpak --version` and store it when the extension starts 
- Show an error message if version < minRequiredVersion for any step that the user might want to try
