### ISSUE TITLE
Rename current `run` to `run-without-rebuild` and current `rebuild` to just `run`

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#63]
Consider removing `flatpak-vscode.rebuild` and move its functionality to `flatpak-vscode.run`.

The rationale is it would be less clutter and confusion with `flatpak-vscode.run`. Additionally, it helps avoid accidentally running without rebuilding.

**Comment by bilelmoussaoui** [comment]
The reason I kept the two steps separate is we don't have a way to track the sources files if there were any changes and you would probably end up waiting a couple of seconds before the app is launched which could be not great :/

**Comment by SeaDve** [comment]
there's probably a vscode api to track modified file

**Comment by bilelmoussaoui** [comment]
The issue is to figure out if those files are part of the source code. That is something normally the build system can know

**Comment by flxzt** [comment]
Please don't get rid of the rebuild / run separation. Sometimes its just convenient to rerun the app to check something even when some files are already modified.

**Comment by SeaDve** [comment]
I see, that makes sense. 

Since the "run" button used in #55 is mapped to rebuild command, it would make sense to rename it to just `run` and rename `run` command to `run-without-rebuild` or something. Mainly for coherency, and to convey semantic oposite of stop

**Comment by bilelmoussaoui** [comment]
I think we can drop rebuild and only keep build here. We know whether the app was built once or not, so we can just make "build" triggers a "rebuild" instead. Make the run button triggers both build & run, and the run command from the palette only triggers run.

**Comment by SeaDve** [comment]
> Make the run button triggers both build & run, and the run command from the palette only triggers run.

I think we want to have the run button to have the same behavior as the command palette one (for coherence), or to atleast have that behavior as an entry in the command palette
