### ISSUE TITLE
Runtime/Build terminals are broken in flatpaked vscode

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#72]
They seem to no longer call `flatpak-spawn` properly 

cc @SeaDve

**Comment by SeaDve** [comment]
Oops, I think it was handled before through `toString`, and now the program name and args are directly access, I'll create a PR

**Comment by bilelmoussaoui** [comment]
yeah fixed it

**Comment by bilelmoussaoui** [comment]
also did a new release
