### ISSUE TITLE
Make the logic for finding manifest more picky

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#74]
gnome-builder validates if the file name of the manifest is a valid app id.

 This is helpful for unnecessary opening of json, yaml, and yml files, which could slow down a lot if you have many of them.

**Comment by bilelmoussaoui** [comment]
That actually makes a lot of sense to have, would be nice to get that implemented before landing your select manifest work. Although, for something like this, it would be nice to also finally start writing some tests, see #29

**Comment by bilelmoussaoui** [comment]
well, we don't need an external dependency. The validation of an app-id is pretty simple =)
