### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#84]
- Rename quiescent to just `isSpinning` or `isOperation`

Currently, it is confusing and hard to spell, apparently

- Rename `FlatpakRunner` to just `Runner` and `FlatpakTerminal` to `OutputTerminal`
- Rename `EXT_ID` with EXTENSION_ID
- Remove a bunch of flatpak prefixes in name (Manager, Map etc.)
- Use consistent test naming
- Rename deactivateIntegrations to unloadIntegrations or something

Some cleanup:
* Move @types/js-yaml to devDependencies

**Comment by SeaDve** [comment]
will handle this when #71 is merged

**Comment by SeaDve** [comment]
@bilelmoussaoui Do we want to remove the flatpak prefix in the manifest?

**Comment by bilelmoussaoui** [comment]
yes that sounds good to me, there will not be a different manifest other than the flatpak one so no need to prefix everything with that
