### ISSUE TITLE
Have a better logging system

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#85]
I'm thinking of something like `rust-analyzer` where it outputs logs with times in an outputChannel. Would it be overkill

**Comment by bilelmoussaoui** [comment]
I would just make sure we `console.log`/`console.warn` wherever we think it could be useful to debug the extension in the future.

**Comment by SeaDve** [comment]
I guess I'll close this then. I had some implementation a few days ago, but not clean.
