### ISSUE TITLE
Runtime/Build terminal should use the same icon as flatpak terminal

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#88]

**Comment by SeaDve** [comment]
Should they have the 'box' icon or the 'terminal' one?

![image](https://user-images.githubusercontent.com/64297935/155874729-d6a94255-5d76-47df-8c15-ffd43edea1b6.png)

![image](https://user-images.githubusercontent.com/64297935/155874738-eec6604c-7dab-4026-a871-74f589c59fef.png)

I do like that the box one looks like a Flatpak logo

**Comment by bilelmoussaoui** [comment]
the package one is what i had in mind

**Comment by SeaDve** [comment]
while we're at it maybe rename the output terminal from `Flatpak` to `Flatpak Output Terminal` or something?

**Comment by SeaDve** [comment]
The Terminal prefix makes it too long, maybe we could also drop `Flatpak` prefix, and just the package icon to differentiate from other terminals
