### ISSUE TITLE
Cleanup build should reset pipeline state

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#90]

**Comment by SeaDve** [comment]
the clean command also calls resetPipelineState after repoDir is deleted

**Comment by SeaDve** [comment]
Does the output terminal get shown when the cleanup build command was ran? I'm suspecting that it is returning earlier before actually doing anything

**Comment by bilelmoussaoui** [comment]
> Does the output terminal get shown when the cleanup build command was ran? I'm suspecting that the command is returning earlier before actually doing anything.

No it doesn't show the command

**Comment by SeaDve** [comment]
The output terminal is not shown?

**Comment by bilelmoussaoui** [comment]
It was already shown because i tried to init a build, i will try to reproduce later

**Comment by SeaDve** [comment]
You could also put a breakpoint there instead of determining if the output terminal was shown. I was just suspecting because of the check:
```js
 if (!this.workspaceState.getInitialized()) {
    return
}
```
it was skipped

**Comment by bilelmoussaoui** [comment]
Oh that is possible, because we didn't had the migration in place yet. Let us see once that PR lands first, maybe there is nothing to be done here

**Comment by bilelmoussaoui** [comment]
This is no longer an issue here
